---
- name: Installing and running on CentOS / Red Hat
  include_tasks: centos_grafana.yaml
  when:
    - ansible_os_family == 'RedHat'

- name: Installing and running on Debian/Ubuntu
  include_tasks: debian_grafana.yaml
  when:
    - ansible_os_family == 'Debian'
